### ISSUE TITLE
Screenshot Issue

### ISSUE THREAD

**Issue by overflowsecurity** [MooseDojo/Serpico#107]
I am adding screenshots based on the WiKi,  

Filename:
1.png

Attachment Name:
1.png

Added it into the proof section of the default template:
[!! 1.png !!]

Will not show up in the word report when generated.  Any ideas?

**Comment by overflowsecurity** [comment]
I now have managed to get the screenshot to appear.  Issue is I can only seem to add one screenshot, and any text I put before or after the screenshot will not appear.

**Comment by BuffaloWill** [comment]
@overflowsecurity, sorry about that. I should add to the Wiki that the image insertion is buggy. Considered removing it because imo it is more effort than it's worth. That is, I find inserting images into my reports one of the shortest parts of the report writing process and the added benefit in doing it from Serpico is limited anyways as the image still has to be resized elsewhere. 

As to troubleshooting, what version of Office are you using? Image insertion is untested on 2016. Common issues that cause the text not to show up would be the formatting surrounding the image (i.e. edit the finding in Serpico and remove text surrounding the image to test) or the template itself breaking the paragraph elements.

**Comment by BuffaloWill** [comment]
@overflowsecurity are you using a default template or a custom template?

**Comment by rameshg** [comment]
Please help me. The exported word document is not showing the screenshots.

**Comment by BuffaloWill** [comment]
@rameshg - Are you using a default template or custom template?
