### ISSUE TITLE
Can import finding multiple times

### ISSUE THREAD

**Issue by toonswyzen** [MooseDojo/Serpico#111]
When I add a current finding to the database i can spam the button X times and the finding will be added X times to the database. Don't know if this is a bug or a feature.

**Comment by BuffaloWill** [comment]
hi @toonswyzen! This is by design. There is no UI method to copy a finding once it's in the Finding Database. A use case would be you write up a super rad awesome XSS finding in your current report and realize you would like multiple versions (e.g. Persistent, Error Based, DOM) in the Finding database.

**Comment by toonswyzen** [comment]
Oh oke thanks for the heads up!
