### ISSUE TITLE
Meta language question

### ISSUE THREAD

**Issue by jtomkiel** [MooseDojo/Serpico#77]
I'm trying to list all the Critical/Highs in a table based on the type.

**æreport/findings_list/findings:::risk<5:::risk>2æ∞title∞** - works great to list all Critical/Highs but now how do I add the TYPE into that formula as well?

e.g. - **æreport/findings_list/findings:::risk<5:::risk>:::type='Web Application'æ∞title∞** doesn't work.

Desired outcome would be:
A table with Vuln name (if it's within the Web Application type), Vulnerability Risk Level (by name - not number), then finally the type printed in 3rd cell.

Can this be done? 

Thanks

**Comment by BuffaloWill** [comment]
Hi! I just pushed a small fix for this though it's kind of ugly. You were close, the issue was that as the docx template is moved to xslt for storage the comparison operator is always set to downcase. So 

```type='Web Application'``` 

would never be true because it was being modified to

```type='web application'```

and xslt does not offer a case insensitive string comparison. One option is to remove the downcase but it would force users to be diligent in their comparison operators (e.g. risk instead of Risk). 

I went with a short term fix to offer this feature and we can decide later about the other options. Basically I added two xslt variables "up" and "low" so that the xslt will perform the case insensitive comparison via translate(). Long story short this should work for you now:

```
æ report/findings_list/findings:::translate(type,$up,$low)=translate('Web Application',$up,$low)æ∞title∞
```

Please test and let me know. Cheers!

**Comment by jtomkiel** [comment]
Thanks for the fast response! After updating, I'm receiving the following error when trying to upload the latest version of my template:

```
Error!! Check the process dump for the error or turn show_exceptions on to show in the web interface.
```

After setting `show_exceptions, true` in serpico.rb I see: 

`Internal Server Error - invalid byte sequence in US-ASCII`

I attempted to add:
```
æreport/findings_list/findings:::risk<5:::risk>2:::translate(type,$up,$low)=translate('Web Application',$up,$low)æ∞title∞
```
Here's how it looks in the table currently:

Vuln Name | Risk | Type
------------ | ------------- | -------------
æreport/findings_list/findings:::risk<5:::risk>2:::translate(type,$up,$low)=translate('Web Application',$up,$low)æ∞title∞ | ∞risk∞ | ∞type∞

**Comment by BuffaloWill** [comment]
Hmm.. Could you create a gist or e-mail me with the first 10 lines of the stack trace? It should be in the output of the terminal when the error is thrown. Thanks!

**Comment by jtomkiel** [comment]
After some additional troubleshooting, it turns out the issue was with something else unrelated within the template. I removed the problem area and only have:

Vuln Name | Risk | Type
------------ | ------------- | -------------
æreport/findings_list/findings:::risk<5:::risk>2:::translate(type,$up,$low)=translate('Web Application',$up,$low)æ∞title∞ | ∞risk∞ | ∞type∞

Now, when I attempt to generate a report I get this error:

![image](https://cloud.githubusercontent.com/assets/10123760/11163922/0a825e98-8ab0-11e5-97c6-77ace8930828.png)

Also, what's the best e-mail address to use to contact you?

**Comment by BuffaloWill** [comment]
Ok, just made my e-mail public on my profile.

**Comment by BuffaloWill** [comment]
This should be good to go, closing.
