### ISSUE TITLE
LDAP Authentication / Session error.

### ISSUE THREAD

**Issue by nanotechz9l** [MooseDojo/Serpico#78]
Serpico throws an error when logging in with valid credentials + valid username in uppercase. 

[ Web UI ]
Error!! Check the process dump for the error or turn show_exceptions on to show in the web interface.

[ Console ]
NoMethodError - undefined method `type' for nil:NilClass:
~/Serpico/model/master.rb:143
~/Serpico.rb:2089:in `is_administrator?'

[ Src:143 ]
return User.first(:username => sess.username).type

[ Src:2089 ]
return true if Sessions.type(session[:session_id]) == "Administrator"

[ Reproduce ]
Enable LDAP mode.
Create valid user account "test" (lowercase).
Login with valid password + user account "TEST" (uppercase). Logging in with invalid password + user account "TEST" (uppercase) will not reproduce error.

[ Workaround ]
Only way to successfully authenticate and gain access to Serpico again is to clear rack.session cookie.

**Comment by BuffaloWill** [comment]
@nanotechz9l thanks for submitting this. I just pushed a fix that forces the case to match exactly in the username. On your end you will need to create a username that matches what is seen by the LDAP server. For example, the username on the Serpico side must be 'TEST' (assuming this is what the username is in AD) instead of 'test'.

**Comment by nanotechz9l** [comment]
Sounds good thanks Will! Confirmed working.
