### ISSUE TITLE
Template Font is Not Retained after Substitution

### ISSUE THREAD

**Issue by sandoi** [MooseDojo/Serpico#87]
First off, AWESOME project! I've been looking for something like this for a long time. Thank you for creating this.

Here is my issue: I noticed that when I generate a report, the font does not get retained for substitution variables. In my case, I have the substitution variable set to the Futura Book font, but when I generate the report it changes it Arial. I also tested by using a "standard" font like Lucida Sans, but I found that instead of changing it to Arial (or staying at Lucida Sans), it gets changed to Calibri. I confirmed that the font is in the template that is stored in Serpico by going to the report template list and choosing the Edit button to view the template.

I am running Serpico on Ubuntu Trusty and have pulled the latest changes as of today. I've tested this on Word 2010 and 2013.

Any ideas?

**Comment by anantshri** [comment]
Based on my experiments what works is if you set your template style specially the normal style to the font you want to keep.

For example if you set normal to Arial everything will be spitted out in Arial.
Simmilarly the idea of using different font is generally associated with different style of text so i would suggest set proper styles and things will be automatically taken care if.

Hope this helps.

**Comment by BuffaloWill** [comment]
@sandoi thanks for the feedback! @anantshri has a good suggestion. I also use Word Styles (https://support.office.com/en-us/article/Style-basics-in-Word-d382f84d-5c38-4444-98a5-9cbb6ede1ba4) to hold the formatting for a paragraph or string of text. Serpico is usually good about respecting styles applied to text. 

Please post back if that works for you. If not, we might have to troubleshoot more.

**Comment by sandoi** [comment]
Thank you both for the input! I will give that a try and post back my results.

**Comment by arisada** [comment]
I agree that some things are very strange with the font/style handling in substituted variables. My template is not very good speaking of styles (there are many parts that do not really use styles but have been "hand-crafted". As a result I had to create a new style for the standard text, because if I changed the "normal" style, I'd completely overwrite the font settings of the first half of the document. Now, there's maybe half of the variables that follow the new style, the code one follows the code style right, but there are some differences between some variables and others. I haven't been able to figure out how to harmonize them, I've tried changing them back and forth to the normal style, etc.
Any idea how it really works ?

**Comment by sandoi** [comment]
I've done some testing, but can't seem to get this to work. I verified that a style is being applied to the text (it's a custom style, but a style nonetheless) and that it's still there when I preview the template in Serpico. However, after the substitution is done, the style is technically still there, but the font gets changed (perhaps it's a character level style being applied over the paragraph style).

Here's what I'm expecting, and maybe you can tell me if this will not be the case:
1. Type a substitution variable (e.g., omega-symbol SOME TEXT omega-symbol), select the whole line (click to the left of the entire line), and apply a style to it
2. Save the template and upload it to Serpico
3. Generate the report
4. Select that same line of text and the exact same style should be applied before the substition was done. This is the step that does not work for me.

Should I expect to do that? I think I should be able to have multiple styles in my template without having to change the Normal style to a different font. Maybe I'm wrong...?

**Comment by BuffaloWill** [comment]
I have a theory about what is happening in most cases. In Microsoft Word, the main content of your document is stored in word/document.xml. When you place a substitution variable like ΩSHORT_COMPANY_NAMEΩ in a template Word may store it in one xml element such as:
```
<w:rFonts w:ascii="Castellar" w:hAnsi="Castellar" w:cs="Aharoni"/>
<w:sz w:val="28"/>
</w:rPr>
<w:t>
ΩSHORT_COMPANY_NAMEΩ</w:t>
</w:r>
```
or it may break it up and store it across multiple elements like so:
```
<w:t>
Ω</w:t>
</w:r>
<w:r w:rsidRPr="000733B5">
<w:rPr>
<w:rFonts w:ascii="Castellar" w:hAnsi="Castellar" w:cs="Aharoni"/>
<w:sz w:val="28"/>
</w:rPr>
<w:t>
SHORT_COMPAN</w:t>
</w:r>
```
To compensate for this, Serpico matches the beginning and ending symbols (Ω to Ω) and then compresses into one XML element. When it does this it can drop tags that exist in between. In the second example above this could end up removing "w:rFonts" tag when performing the compression. Style tags are less likely to be removed because the style is applied at the beginning of the paragraph element. However, it can still happen in either case. 

@sandoi you are correct that Serpico can and should respect a style applied to a set of text containing a substitution variable. Could you verify that there are no other fonts mixed into the line of text? A font can override the style if they are mixed. As you mentioned, the generated report will show the style applied but the font will be different. The "format painter" is a good tool to use in the template to make sure that the entire line has a style correctly applied with no other fonts.

**Comment by sandoi** [comment]
Below is a portion of the template that I'm using, which uses a FULL_COMPANY_NAME variable. I notice the w:rFonts element using the Calibri font:
```xml
<w:p w14:paraId="3CB78AA9" w14:textId="50E3E3F9" w:rsidR="002B48F7" w:rsidRPr="00D038E9" w:rsidRDefault="00B12E2C" w:rsidP="00D038E9">
<w:pPr>
<w:pStyle w:val="StyleFuturaBook22ptLeft131After6pt" /> 
</w:pPr>
<w:r w:rsidRPr="00D038E9">
<w:rPr>
<w:rFonts w:ascii="Calibri" w:hAnsi="Calibri" w:cs="Calibri" /> 
</w:rPr>
<w:t>Ω</w:t> 
</w:r>
<w:r w:rsidRPr="00D038E9">
<w:t>FULL_CO</w:t> 
</w:r>
<w:bookmarkStart w:id="0" w:name="_GoBack" /> 
<w:bookmarkEnd w:id="0" /> 
<w:r w:rsidRPr="00D038E9">
<w:t>MPANY_NAME</w:t> 
</w:r>
<w:r w:rsidRPr="00D038E9">
<w:rPr>
<w:rFonts w:ascii="Calibri" w:hAnsi="Calibri" w:cs="Calibri" /> 
</w:rPr>
<w:t>Ω</w:t> 
</w:r>
</w:p>
```
I imagine if I got rid of the font elements my styling would be maintained. I did use the format painter to apply the style I wanted, but it seems the font element keeps getting added somehow.

**Comment by BuffaloWill** [comment]
Did you try clearing all formatting from the text? Home > Font > Clear All Formatting or Ctrl+Space on the  highlighted text.
If you want to dig further, the corresponding XSLT in templates/ has what Serpico creates and uses after the template has been uploaded. The xslt's are randomly named but you can grep to find the one you want or going to the database and running 'select * from xslts;' to find the associated xslt.
