### ISSUE TITLE
Nessus ID Should Be Included in Nessus Data Upload

### ISSUE THREAD

**Issue by BuffaloWill** [MooseDojo/Serpico#98]
As a user I would like the Nessus ID to be included with the finding when the scan data is uploaded. Currently I must upload the finding into the template database and then assign a master id to the finding to make it reusable.

Originally from https://github.com/MooseDojo/Serpico/issues/88 

Dev Thoughts:
This is currently not possible as a nessus master id is only associated with a Findings object and not TemplateFindings object. It could be done by setting a temporal master id to Findings and then associating when the user attempts to upload to master database.

**Comment by mcjon3z** [comment]
Thinking a bit further about my previous request as an end user, in most cases in which a Nessus finding would go into my report it would go in directly as-imported and may not really provide much benefit as I initially thought by dumping it into the templated findings. I suppose the one benefit of adding them all to templated findings as they are imported would be to customize the remediation effort and finding type so those did not have to be manually edited after each import.

If you did ultimately decide to track within the DB schema, some options I thought of (all of which have their own sets of issues):
- Add fields for Nessus ID and Burp ID to the findings table - this could get messy in the future as I would foresee additional import options being added which would require additional fields
- Add single field for temporal association and indicate tool as part of the ID with a delimiter (e.g. n_543221, b_12345) - maybe the quickest and dirtiest solution to handle with a single table column
- Add separate mapping tables similar to nessus_mappings and burp_mappings to associate with findings; once again, could get messy if new import functions are added which would require 2 new tables for each tool (one for template association and one for finding association)
- Modify existing mapping schema to facilitate associating multiple tools with both templates and findings. This would most definitely be the biggest pain but could provide additional flexibility for future additions and enhancements if down the road you have 10 import routines instead of 2.
- Instead of ever adding the imported items to the template table, maintain separate tables for each tool's imported plugin data which are automatically added / updated any time an import is conducted. In this case, the ID field could then match the plugin ID instead of being autonumber. This keeps the templated findings database from getting polluted with 5000 nessus plugins but still allows the user to tweak types and remediation efforts and have those values retained. The end user is probably never going to manually add a templated finding that was created from an imported Nessus or Burp vulnerability anyway. As an extension, this could also track an "ignore" field (never import this plugin into my report in the future). May could use the existing mappings tables to hold all this if under the assumption that each plugin will only be mapped to one templated finding.

An alternative idea just to make the plugin ID easily available after being imported would be to include the plugin ID at the top of the Notes field at import where you could easily grab it and copy/paste into the nessus mapping field (note you would still have to go into the report item to grab the plugin ID before moving to the template).
